-- MySQL Script generated by MySQL Workbench
-- Wed Mar 24 02:42:44 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema CLIENTE
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CLIENTE
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CLIENTE` DEFAULT CHARACTER SET utf8 ;
USE `CLIENTE` ;

-- -----------------------------------------------------
-- Table `CLIENTE`.`CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CLIENTE`.`CLIENTE` (
  `CLI_COD` INT NOT NULL AUTO_INCREMENT,
  `CLI_NOME` VARCHAR(100) NULL,
  `CLI_CPF` VARCHAR(20) NULL,
  `CLI_DT_NASC` DATE NULL,
  `CLI_SEXO` VARCHAR(1) NULL,
  `CLI_FONE` VARCHAR(20) NULL,
  PRIMARY KEY (`CLI_COD`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CLIENTE`.`LOGIN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CLIENTE`.`LOGIN` (
  `LOG_SEQ` INT NOT NULL AUTO_INCREMENT,
  `LOG_NOME` VARCHAR(30) NULL,
  `LOG_SENHA` VARCHAR(20) NULL,
  PRIMARY KEY (`LOG_SEQ`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
